CREATE TABLE State(
	StateId INT IDENTITY PRIMARY KEY,
	StateName VARCHAR(50) NOT NULL,
	Abbreviation VARCHAR(20),
	StateCapital VARCHAR(50),
	CountryID INT FOREIGN KEY REFERENCES Country(CountryId)
)

INSERT INTO State
VALUES
	('Andhra Pradesh', 'AP', 'Amaravati', 75),
	('Arunachal Pradesh', 'AR', 'Itanagar', 75),
	('Assam', 'AS', 'Dispur', 75),
	('Bihar', 'BR', 'Patna', 75),
	('Chhattisgarh', 'CG', 'Raipur', 75),
	('Goa', 'GA', 'Panaji', 75),
	('Gujarat', 'GJ', 'Gandhinagar', 75),
	('Haryana', 'HR', 'Chandigarh', 75),
	('Himachal Pradesh', 'HP', 'Shimla', 75),
	('Jharkhand', 'JH', 'Ranchi', 75),
	('Karnataka', 'KA', 'Bengaluru', 75),
	('Kerala', 'KL', 'Thiruvananthapuram', 75),
	('Madhya Pradesh', 'MP', 'Bhopal', 75),
	('Maharashtra', 'MH', 'Mumbai', 75),
	('Manipur', 'MN', 'Imphal', 75),
	('Meghalaya', 'ML', 'Shillong', 75),
	('Mizoram', 'MZ', 'Aizawl', 75),
	('Nagaland', 'NL', 'Kohima', 75),
	('Odisha', 'OD', 'Bhubaneswar', 75),
	('Punjab', 'PB', 'Chandigarh', 75),
	('Rajasthan', 'RJ', 'Jaipur', 75),
	('Sikkim', 'SK', 'Gangtok', 75),
	('Tamil Nadu', 'TN', 'Chennai', 75),
	('Telangana', 'TG', 'Hyderabad', 75),
	('Tripura', 'TR', 'Agartala', 75),
	('Uttar Pradesh', 'UP', 'Lucknow', 75),
	('Uttarakhand', 'UT', 'Dehradun', 75),
	('West Bengal', 'WB', 'Kolkata', 75),
	('Andaman and Nicobar Islands', 'AN', 'Port Blair', 75),
	('Chandigarh', 'CH', 'Chandigarh', 75),
	('Dadra and Nagar Haveli and Daman and Diu', 'DN', 'Daman', 75),
	('Delhi', 'DL', 'New Delhi', 75),
	('Jammu and Kashmir', 'JK', 'Srinagar', 75),
	('Lakshadweep', 'LD', 'Kavaratti', 75),
	('Ladakh', 'LA', 'Leh', 75),
	('Puducherry', 'PY', 'Puducherry', 75),
	('Western Province', 'WP', 'Colombo', 163),
	('Central Province', 'CP', 'Kandy', 163),
	('Southern Province', 'SP', 'Galle', 163),
	('Northern Province', 'NP', 'Jaffna', 163),
	('Eastern Province', 'EP', 'Trincomalee', 163),
	('North Western Province', 'NWP', 'Kurunegala', 163),
	('North Central Province', 'NCP', 'Anuradhapura', 163),
	('Uva Province', 'UP', 'Badulla', 163),
	('Sabaragamuwa Province', 'SP', 'Ratnapura', 163),
	('Province No. 1', 'P1', 'Biratnagar', 123),
	('Province No. 2', 'P2', 'Janakpur', 123),
	('Bagmati Province', 'P3', 'Hetauda', 123),
	('Gandaki Province', 'P4', 'Pokhara', 123),
	('Province No. 5', 'P5', 'Butwal', 123),
	('Karnali Province', 'P6', 'Birendranagar', 123),
	('Sudurpashchim Province', 'P7', 'Dipayal', 123),
	('Alberta', 'AB', 'Edmonton', 31),
	('British Columbia', 'BC', 'Victoria', 31),
	('Manitoba', 'MB', 'Winnipeg', 31),
	('New Brunswick', 'NB', 'Fredericton', 31),
	('Newfoundland and Labrador', 'NL', 'St. John''s', 31),
	('Northwest Territories', 'NT', 'Yellowknife', 31),
	('Nova Scotia', 'NS', 'Halifax', 31),
	('Nunavut', 'NU', 'Iqaluit', 31),
	('Ontario', 'ON', 'Toronto', 31),
	('Prince Edward Island', 'PE', 'Charlottetown', 31),
	('Quebec', 'QC', 'Quebec City', 31),
	('Saskatchewan', 'SK', 'Regina', 31),
	('Yukon', 'YT', 'Whitehorse', 31),
	('Moscow', 'MC', 'Moscow', 142),
	('Saint Petersburg', 'SP', 'Saint Petersburg', 142),
	('Republic of Adygea', 'AD', 'Maykop', 142),
	('Republic of Altai', 'AL', 'Gorno-Altaysk', 142),
	('Altai Krai', 'AK', 'Barnaul', 142),
	('Amur Oblast', 'AO', 'Blagoveshchensk', 142),
	('Arkhangelsk Oblast', 'AR', 'Arkhangelsk', 142),
	('Astrakhan Oblast', 'AS', 'Astrakhan', 142),
	('Belgorod Oblast', 'BE', 'Belgorod', 142),
	('Bryansk Oblast', 'BR', 'Bryansk', 142),
	('Republic of Buryatia', 'BU', 'Ulan-Ude', 142),
	('Chechen Republic', 'CE', 'Grozny', 142),
	('Sindh', 'SD', 'Karachi', 131),
	('Khyber Pakhtunkhwa', 'KP', 'Peshawar', 131),
	('Balochistan', 'BA', 'Quetta', 131),
	('Azad Jammu and Kashmir', 'AJK', 'Muzaffarabad', 131),
	('Gilgit-Baltistan', 'GB', 'Gilgit', 131),
	('Dhaka Division', 'DD', 'Dhaka', 14),
	('Chittagong Division', 'CD', 'Chittagong', 14),
	('Khulna Division', 'KD', 'Khulna', 14),
	('Barisal Division', 'BD', 'Barisal',14 ),
	('Sylhet Division', 'SD', 'Sylhet', 14),
	('Rajshahi Division', 'RD', 'Rajshahi', 14),
	('Rangpur Division', 'RD', 'Rangpur', 14),
	('Kabul', 'KB', 'Kabul', 1),
	('Herat', 'HT', 'Herat', 1),
	('Balkh', 'BK', 'Mazar-i-Sharif', 1),
	('Kandahar', 'KD', 'Kandahar', 1),
	('Nangarhar', 'NG', 'Jalalabad', 1),
	('Thimphu', 'TH', 'Thimphu', 20),
	('Punakha', 'PK', 'Punakha', 20),
	('Paro', 'PA', 'Paro', 20),
	('Bumthang', 'BM', 'Jakar', 20),
	('Alabama', 'AL', 'Montgomery', 185),
	('Alaska', 'AK', 'Juneau', 185),
	('Arizona', 'AZ', 'Phoenix', 185),
	('Arkansas', 'AR', 'Little Rock', 185),
	('California', 'CA', 'Sacramento', 185),
	('Colorado', 'CO', 'Denver', 185),
	('Connecticut', 'CT', 'Hartford', 185),
	('Delaware', 'DE', 'Dover', 185),
	('Florida', 'FL', 'Tallahassee', 185),
	('Georgia', 'GA', 'Atlanta', 185),
	('Hawaii', 'HI', 'Honolulu', 185),
	('Idaho', 'ID', 'Boise', 185),
	('Illinois', 'IL', 'Springfield', 185),
	('Indiana', 'IN', 'Indianapolis', 185),
	('Iowa', 'IA', 'Des Moines', 185),
	('Kansas', 'KS', 'Topeka', 185),
	('Kentucky', 'KY', 'Frankfort', 185),
	('Louisiana', 'LA', 'Baton Rouge', 185),
	('Maine', 'ME', 'Augusta', 185),
	('Maryland', 'MD', 'Annapolis', 185),
	('Massachusetts', 'MA', 'Boston', 185),
	('Michigan', 'MI', 'Lansing', 185),
	('Minnesota', 'MN', 'St. Paul', 185),
	('Mississippi', 'MS', 'Jackson', 185),
	('Missouri', 'MO', 'Jefferson City', 185),
	('Montana', 'MT', 'Helena', 185),
	('Nebraska', 'NE', 'Lincoln', 185),
	('Nevada', 'NV', 'Carson City', 185),
	('New Hampshire', 'NH', 'Concord', 185),
	('New Jersey', 'NJ', 'Trenton', 185),
	('New Mexico', 'NM', 'Santa Fe', 185),
	('New York', 'NY', 'Albany', 185),
	('North Carolina', 'NC', 'Raleigh', 185),
	('North Dakota', 'ND', 'Bismarck', 185),
	('Ohio', 'OH', 'Columbus', 185),
	('Oklahoma', 'OK', 'Oklahoma City', 185),
	('Oregon', 'OR', 'Salem', 185),
	('Pennsylvania', 'PA', 'Harrisburg', 185),
	('Rhode Island', 'RI', 'Providence', 185),
	('South Carolina', 'SC', 'Columbia', 185),
	('South Dakota', 'SD', 'Pierre', 185),
	('Tennessee', 'TN', 'Nashville', 185),
	('Texas', 'TX', 'Austin', 185),
	('Utah', 'UT', 'Salt Lake City', 185),
	('Vermont', 'VT', 'Montpelier', 185),
	('Virginia', 'VA', 'Richmond', 185),
	('Washington', 'WA', 'Olympia', 185),
	('West Virginia', 'WV', 'Charleston', 185),
	('Wisconsin', 'WI', 'Madison', 185),
	('Wyoming', 'WY', 'Cheyenne', 185);




UPDATE State
SET CountryID = 123
WHERE
CountryID = 97

SELECT *  FROM State
WHERE CountryID = 75

SELECT  COUNT(StateName) AS Total, CountryID
FROM State
WHERE CountryID = 75
GROUP BY CountryID
ORDER BY COUNT(StateName) DESC;


DROP TABLE State


